### ISSUE TITLE
read_CensoEscolar fails unless file option is provided

### ISSUE THREAD

**Issue by raphael-gouvea** [lucasmation/microdadosBrasil#149]
The read_CensoEscolar only works if one provides the file argument. There must be some issue with the folder structure. Also, reading the "escola" file type returns some warnings. It seems that there is a problem there too.

library(microdadosBrasil)
censo.path<-"/home/raphael/Desktop/MicroBrasil/"
# Censo Escolar
download_sourceData('CensoEscolar', 2005, unzip=T,root_path=censo.path)
# Failed read
escola <- read_CensoEscolar('escola',2005,harmonize_varnames=T,root_path=censo.path)
prof <-read_CensoEscolar('escola_educprof',2005,harmonize_varnames=T,root_path=censo.path)

# Read using file
escola.file.path<-paste0(censo.path,"microdados_censo_escolar_2005/DADOS/CENSOESC_2005")
escola <- read_CensoEscolar(ft="escola",i=2005,file=paste0(escola.file.path,"/CENSOESC_2005.TXT"))

prof.file.path<-paste0(censo.path,"microdados_censo_escolar_2005/DADOS/")
prof<-read_CensoEscolar(ft="escola_educprof",i=2005,file=paste0(prof.file.path,"/EDUCPROF_2005.TXT"))

**Comment by nicolassoarespinto** [comment]
@raphael-gouvea  I think the problem was actually related to the argument `harmonize_varnames = T`. If that is the case, should be working now.  I will close the Issue as your sample code is working for me, but if I missed something, please reopen the Issue and I can look again.( and I hope to not delay 3 months this time, sorry about that)
