### ISSUE TITLE
error installing the package

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/microdadosBrasil#83]
> devtools::install_github("lucasmation/microdadosBrasil")
Downloading GitHub repo lucasmation/microdadosBrasil@master
from URL https://api.github.com/repos/lucasmation/microdadosBrasil/zipball/master
Installing microdadosBrasil
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/r342471958/AppData/Local/Temp/RtmpUdb7Hu/devtools102440056502/lucasmation-microdadosBrasil-3d7133d"  \
  --library="C:/Users/r342471958/Documents/R/win-library/3.3"  \
  --install-tests 

* installing *source* package 'microdadosBrasil' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'chron'
ERROR: lazy loading failed for package 'microdadosBrasil'
* removing 'C:/Users/r342471958/Documents/R/win-library/3.3/microdadosBrasil'
Error: Command failed (1)

**Comment by lucasmation** [comment]
even with: 

install.packages('chron')
devtools::install_github("lucasmation/microdadosBrasil")

I get error: 

> devtools::install_github("lucasmation/microdadosBrasil")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached

(maybe it is github not sending the requested package?)

**Comment by lucasmation** [comment]
another problem, after installing: 

download_sourceData("RAIS", i = "2000",)
Error in loadNamespace(name) : there is no package called ‘RCurl’

should also be in the dependencies, no?

**Comment by nicolassoarespinto** [comment]
@lucasmation 

### About `chron`:

This `chron` dependency is really strange because we do not use it  anywhere.

To confirm, i uninstalled `chron` and loaded `microdadosBrasil` and it worked both using `library(microdadosBrasil)` and `devtools::load_all()`.

I think maybe it is needed to use `devtools::install_github` 

### About `RTools`: 

 it is a not so used package and we use it only for downloading RAIS. So maybe we should put in documentation just as a suggested package and not as a dependency. As suggeste [here](http://r-pkgs.had.co.nz/description.html#dependencies)

**Comment by lucasmation** [comment]
chron must be a dependency of RCurl.
Why not just add Rcurl? is there any problem with adding it?

2016-10-13 16:54 GMT-03:00 nicolassoarespinto <notifications@github.com>:

**Comment by nicolassoarespinto** [comment]
@lucasmation the only reason it is because is not so widely used as  `tidyverse` packages, so it would turn our package more difficult to install. But we could add it if you think it is the better solution.

**Comment by lucasmation** [comment]
Ok, please add it

Em qui, 13 de out de 2016 1:22 PM, nicolassoarespinto <
notifications@github.com> escreveu:

**Comment by lucasmation** [comment]
I mean, add it to the list of packages that is automatically installed with
the package

Em qui, 13 de out de 2016 1:43 PM, Lucas Ferreira Mation <
lucasmation@gmail.com> escreveu:

**Comment by nicolassoarespinto** [comment]
Fixed in #84 . I also verified that `chron` is a `data.table` dependecy. For some reason it is not installed when we use just `data.table` as the dependency.

As we should have this problem with other indirect dependecies( as in #68) i used [miniCRAN](http://blog.revolutionanalytics.com/2014/07/dependencies-of-popular-r-packages.html) to verify all packages we need to use `microdadosBrasil` . The result is in the image below. @lucasmation  do you think we should add all this packages as explicit dependencies in DESCRIPTION?

![microdadosbrasil](https://cloud.githubusercontent.com/assets/10147479/19395286/497e4d58-9213-11e6-85b6-a4db5de75bff.png)
